type TaskPriorities = {[key in TaskType]: number};

const TASK_PRIORITIES: TaskPriorities = {
  TASK_PIONEER_PROVINCE: 50,
  TASK_MINE_ENERGY: 100,
  TASK_TRANSPORT_ENERGY: 150,
  TASK_BUILD_CONTAINER_FOR_MINE: 200,
  TASK_BUILD_STRUCTURE: 250,
  TASK_UPGRADE_CONTROLLER: 300,
  TASK_EXTRACT_MINERAL: 400,
  TASK_SCOUT_DYNAMIC: 500
};

export default TASK_PRIORITIES;
