export const TASK_BOOTSTRAP_PROVINCE = 'TASK_BOOTSTRAP_PROVINCE';
export const TASK_BUILD_CONTAINER_FOR_MINE = 'TASK_BUILD_CONTAINER_FOR_MINE';
export const TASK_MINE_ENERGY = 'TASK_MINE_ENERGY';
export const TASK_TRANSPORT_ENERGY = 'TASK_TRANSPORT_ENERGY';
export const TASK_EXTRACT_MINERAL = 'TASK_EXTRACT_MINERAL';
export const TASK_SCOUT_DYNAMIC = 'TASK_SCOUT_DYNAMIC';
