import * as TASK_CONSTANTS from './TasksConstants';

const TASK_PRIORITIES = {
  [TASK_CONSTANTS.TASK_BOOTSTRAP_PROVINCE]: 10,
  [TASK_CONSTANTS.TASK_MINE_ENERGY]: 30,
  [TASK_CONSTANTS.TASK_TRANSPORT_ENERGY]: 50,
  [TASK_CONSTANTS.TASK_BUILD_CONTAINER_FOR_MINE]: 70,
  [TASK_CONSTANTS.TASK_EXTRACT_MINERAL]: 100,
  [TASK_CONSTANTS.TASK_SCOUT_DYNAMIC]: 200
};

export default TASK_PRIORITIES;
