export const SETTLER_PIONEER = 'SETTLER_PIONEER';
export const SETTLER_MINER = 'SETTLER_MINER';
export const SETTLER_CARRIER = 'SETTLER_CARRIER';
export const SETTLER_WORKER = 'SETTLER_WORKER';
export const SETTLER_SCOUT = 'SETTLER_SCOUT';
export const SETTLER_WARDEN = 'SETTLER_WARDEN';
export const SETTLER_LORD = 'SETTLER_LORD';
