import * as SETTLER_CONSTANTS from './SettlerConstants';

const SETTLER_NAMES = {
  [SETTLER_CONSTANTS.SETTLER_CARRIER]: 'Carrier',
  [SETTLER_CONSTANTS.SETTLER_MINER]: 'Miner',
  [SETTLER_CONSTANTS.SETTLER_PIONEER]: 'Pioneer',
  [SETTLER_CONSTANTS.SETTLER_WORKER]: 'Worker',
  [SETTLER_CONSTANTS.SETTLER_SCOUT]: 'Scout'
};

export default SETTLER_NAMES;
