type DISTRICT_CAPITAL = 'DISTRICT_CAPITAL';
type DISTRICT_QUARRY = 'DISTRICT_QUARRY';
type DISTRICT_OUTPOST = 'DISTRICT_OUTPOST';
type DISTRICT_FORT = 'DISTRICT_FORT';
type DISTRICT_NONE = 'DISTRICT_NONE';
type DISTRICT_OCCUPIED = 'DISTRICT_OCCUPIED';

type DistrictType = DISTRICT_CAPITAL
  | DISTRICT_QUARRY
  | DISTRICT_OUTPOST
  | DISTRICT_FORT
  | DISTRICT_NONE
  | DISTRICT_OCCUPIED;
