type SETTLER_PIONEER = 'SETTLER_PIONEER';
type SETTLER_MINER = 'SETTLER_MINER';
type SETTLER_CARRIER = 'SETTLER_CARRIER';
type SETTLER_WORKER = 'SETTLER_WORKER';
type SETTLER_SCOUT = 'SETTLER_SCOUT';
type SETTLER_WARDEN = 'SETTLER_WARDEN';
type SETTLER_LORD = 'SETTLER_LORD';


type SettlerRole =
  SETTLER_PIONEER
  | SETTLER_MINER
  | SETTLER_CARRIER
  | SETTLER_WORKER
  | SETTLER_SCOUT
  | SETTLER_WARDEN
  | SETTLER_LORD;
