type SETTLER_PIONEER = 'SETTLER_PIONEER';
type SETTLER_MINER = 'SETTLER_MINER';
type SETTLER_CARRIER = 'SETTLER_CARRIER';
type SETTLER_WORKER = 'SETTLER_WORKER';
type SETTLER_SCOUT = 'SETTLER_SCOUT';


type SettlerRole =
  SETTLER_PIONEER
  | SETTLER_MINER
  | SETTLER_CARRIER
  | SETTLER_WORKER
  | SETTLER_SCOUT;
