type TASK_PIONEER_PROVINCE = 'TASK_PIONEER_PROVINCE';
type TASK_BUILD_CONTAINER_FOR_MINE = 'TASK_BUILD_CONTAINER_FOR_MINE';
type TASK_MINE_ENERGY = 'TASK_MINE_ENERGY';
type TASK_TRANSPORT_ENERGY = 'TASK_TRANSPORT_ENERGY';
type TASK_EXTRACT_MINERAL = 'TASK_EXTRACT_MINERAL';
type TASK_SCOUT_DYNAMIC = 'TASK_SCOUT_DYNAMIC';
type TASK_BUILD_STRUCTURE = 'TASK_BUILD_STRUCTURE';

type TaskType =
  TASK_PIONEER_PROVINCE
  | TASK_BUILD_CONTAINER_FOR_MINE
  | TASK_EXTRACT_MINERAL
  | TASK_MINE_ENERGY
  | TASK_TRANSPORT_ENERGY
  | TASK_SCOUT_DYNAMIC
  | TASK_BUILD_STRUCTURE;
