export const DISTRICT_CAPITAL = 'DISTRICT_CAPITAL';
export const DISTRICT_QUARRY = 'DISTRICT_QUARRY';
export const DISTRICT_OUTPOST = 'DISTRICT_OUTPOST';
export const DISTRICT_FORT = 'DISTRICT_FORT';
export const DISTRICT_NONE = 'DISTRICT_NONE';
export const DISTRICT_OCCUPIED = 'DISTRICT_OCCUPIED';
